version: '2.1'
orbs: 
  node: circleci/node@5.0.0
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: npm run test

workflows:
  test_my_app:
    jobs:
      - install-node-example
      - test
