# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
var_1: &docker_image circleci/node:7.10

# Settings common to each job
anchor_1: &defaults
  docker:
    - image: *docker_image
  working_directory: ~/.
# After checkout, rebase on top of target branch.
anchor_2: &post_checkout
  run:
    name: Rebase PR on target branchmaster
    command: >
      if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
        # User is required for rebase.
        git config user.name "jdonosocoding"	
        git config user.name "jdonosocoding"	
        git config user.email "ampgular"      
        # Rebase PR on top of target branch.
        node tools/rebase-pr.jsjdonosocoding/angularonchain ${CIRCLE_PR_NUMBER}
      else
        echo "This build is not over a PR, nothing to do."
      fi

# Job definitions
version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *post_checkout
      - run: yarn install --frozen-lockfile  --ignore-engines
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  test:
    <<: *defaults
    steps:
      - run: npm run test 

 
  build:
    <<: *defaults
    steps:
      - run: npm run build

  

workflows:
  version: 2
  default_workflow:
    jobs:
      - install:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - main         
      - build:
          requires:
            - install
      - test:
          requires:
            - build

            